name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 'Build 🧱'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Build Application 🧱
        run: bun run build

  lint:
    name: 'Lint 🐱'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Lint JS files 🐱
        run: bun run lint:js

      - name: Typecheck 🐱
        run: bun run typecheck

  test:
    name: 'Test 🧪'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup 👨🏻‍💻
        uses: ./.github/actions/setup

      - name: Run unit tests 🧪
        run: bun run test:coverage

      - name: Collect coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
